server:
  port: 80
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///poor_trip?characterEncoding=utf-8&useSSL=false
    username: root
    password:
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yp.entity
  type-handlers-package: com.yp.mybatis

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

shiro:
  loginUrl: /user/login-ui
  unauthorizedUrl: /user/401

pic:
  types: .jpg,.png,.gif,.jpeg
  path: /Users/yangpeng/Documents/picTest/
